# Generated by Django 3.0.9 on 2023-07-16 13:53

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promptlog',
            name='prompt',
            field=jsonfield.fields.JSONField(max_length=200),
        ),
    ]
