# Generated by Django 3.0.9 on 2023-07-18 08:28

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0003_auto_20230716_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptlog',
            name='sensitive_data',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=50, null=True)),
        ),
    ]
